# Disable ctrl-s and ctrl-q
stty -ixon

# Alias definitions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# utils for git
source /usr/lib/git-core/git-sh-prompt
source $HOME/.git-completion.bash

# PS1 terminal prompt
PS1="[\[\033[01;32m\]jovyan@docker \[\033[00m\]\[\033[01;34m\]\W\[\033[00m\]"
PS1="$PS1\$(__git_ps1 ' \[\033[0;31m\]%s\[\033[00m\]')]\$ "
